### ISSUE TITLE
RCTImageLoader 

### ISSUE THREAD

**Issue by Phenek** [alexmngn/react-native-image-crop#6]
Hello guys,

I just upgrade to RN 0.40, and
I'm trying to use your package but I got this error on xcode:
[RCTImageLoader _loadImageOrDataWithURLRequest:size:scale:resizeMode:progressBlock:partialLoadBlock:completionBlock:]_block_invoke.194 + 355
libc++abi.dylib: terminating with uncaught exception of type NSException

My dependencies: {
    "gl-react": "^2.2.4",
    "gl-react-image": "0.0.2",
    "gl-react-native": "^2.40.1",
    "react": "15.4.2",
    "react-native": "<=0.40.0",
    "react-native-camera": "git+https://github.com/lwansbrough/react-native-camera.git",
    "react-native-image-resizer": "^0.1.0",
    "react-native-image-crop": "^1.0.2",
    "react-native-router-flux": "^3.37.0"
  },

Hope you can help me.
regards,

**Comment by alexmngn** [comment]
I just tried to install the component on a brand new project and runs fine on iOS 10 simulator. 

This is my package.json dependencies:

```
  "dependencies": {
    "react": "~15.4.0-rc.4",
    "react-native": "0.40.0",
    "react-native-image-crop": "^1.0.2",
    "react-native-image-resizer": "^0.1.0"
  },
```

Your issue might be coming from something else... Maybe `gl`?

**Comment by Phenek** [comment]
First of all Thanks to answer.
Did you use it like below? maybe the error come from me!
```
import React, { Component } from 'react'
import {
  Text,
  View,
  Image,
  StyleSheet
} from 'react-native'
import { Actions } from 'react-native-router-flux';
import ImageCrop from 'react-native-image-crop';

export default class CropContainer extends Component {
   constructor(props) {
      super(props);
      this.state = {
        image: require('../../pictures/test.jpg'),
        height: 0,
        widht: 0,
        zoom: 0
      }
   }

   capture(){
     this.imageCrop.crop().then((uri) => {
      // uri contains the cropped image
    });
   }

   render() {
      return (
        <View>
          <ImageCrop
            ref={(c) => { this.imageCrop = c; }}
            cropWidth={500}
            cropHeight={500}
            source={this.state.image}
            />
            <Text onPress={this.capture.bind(this)}>Capture()</Text>
        </View>
      );
   }
}
```
Let me know ;-)

**Comment by alexmngn** [comment]
I used the example code you can find here: https://github.com/alexmngn/react-native-image-crop/blob/master/Example/src/App.js

You should not import the image in the state of your app, that's quite a very bad way to manage this. Something like this is more correct:

```
import image from '../../pictures/test.jpg';

...

<ImageCrop
  source={image}
/>
```

**Comment by Phenek** [comment]
OKay thanks for taking time with me ;-)
Problem Solved
