### ISSUE TITLE
Use async await instead of Promise

### ISSUE THREAD

**Issue by sibelius** [alexmngn/react-native-image-crop#8]
Async await methods makes the code more readable

can we switch to spaces as well? it makes the code better on github \o/

**Comment by alexmngn** [comment]
Feel free to create a pull request to replace the Promise with async/await.

If github doesn't make the tabs look great, that's unfortunately sad. You can append ?ts=2 or ?ts=4 to the URL to change the tab-size. Tabs over spaces is great to let developers decide the size of indentation they are more comfortable to use on their editor. 
https://www.youtube.com/watch?v=SsoOG6ZeyUI
